import topologyData from '../data/bracket.2026.json';
import type { BracketTopology } from './types';

const TOPOLOGY = topologyData as unknown as BracketTopology;

/** The bundled knockout bracket topology (generated by gen:schedule). */
export function loadBracketTopology(): BracketTopology {
  return TOPOLOGY;
}
