/**
 * 0.11 · 2.2 — the refresher reads the schedule slice it carries with the
 * competition's written team kind, like every other reader of a cached match.
 *
 * Off the bundle a cycle that only reads live scores carries the slice's
 * display records through, sealed. For a nations competition (the Nations
 * League) those records are nations: written back with their generated flags;
 * for a club competition, written back with none.
 */
import { mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import type { Match } from '@claudinho/core';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { cachePath, type CacheState, writeState } from '../src/cache';
import { runRefresh } from '../src/refresh';

const SOURCE = 'espn';
const NOW = Date.parse('2026-10-10T15:00:00.000Z');
const MIN = 60_000;
const iso = (ms: number) => new Date(ms).toISOString();

let dir: string;
const ORIG = process.env.XDG_CACHE_HOME;
beforeEach(() => {
  dir = mkdtempSync(join(tmpdir(), 'claudinho-refresher-kind-'));
  process.env.XDG_CACHE_HOME = dir;
  // Every request answers an empty day: the cycle reads live scores and finds none.
  vi.stubGlobal('fetch', async () =>
    new Response(JSON.stringify({ leagues: [{ season: { year: 2026 } }], events: [] }), {
      status: 200,
      headers: { 'content-type': 'application/json' },
    }),
  );
});
afterEach(() => {
  vi.unstubAllGlobals();
  if (ORIG === undefined) delete process.env.XDG_CACHE_HOME;
  else process.env.XDG_CACHE_HOME = ORIG;
  rmSync(dir, { recursive: true, force: true });
});

/** A snapshot whose discovery is fresh and whose one fixture is in its window: the cycle only reads live scores. */
function seed(competition: string, home: [string, string], away: [string, string]) {
  const kickoff = iso(NOW - 30 * MIN);
  // Stored WITHOUT flags: a flag in the file afterwards was generated by the refresher's seal.
  const fixture = {
    id: '700500',
    stage: 'LEAGUE',
    kickoff,
    venue: 'Somewhere',
    home: { code: home[0], name: home[1], id: `espn:${home[0]}1` },
    away: { code: away[0], name: away[1], id: `espn:${away[0]}2` },
    status: 'SCHEDULED',
    updatedAt: iso(NOW - 10 * MIN),
  } as unknown as Match;
  const state: CacheState = {
    updatedAt: iso(NOW - MIN),
    live: [],
    degraded: false,
    source: SOURCE,
    competition,
    schedule: {
      index: [{ id: '700500', kickoff, on: true }],
      fixtures: [fixture],
      updatedAt: iso(NOW - 10 * MIN),
      attemptedAt: iso(NOW - 10 * MIN),
      failures: 0,
      complete: true,
    },
  };
  writeState(state, NOW - MIN);
}
const written = (competition: string) =>
  JSON.parse(readFileSync(cachePath(SOURCE, competition), 'utf8')) as CacheState;

describe('the refresher carries the display records sealed with the competition kind', () => {
  it('a nations competition: the records it writes back are flagged from their names', async () => {
    seed('uefa.nations', ['ALB', 'Albania'], ['LVA', 'Latvia']);
    await runRefresh({ source: SOURCE, competition: 'uefa.nations', now: new Date(NOW), jitterMs: 0 });
    const out = written('uefa.nations');
    expect(out.updatedAt).not.toBe(iso(NOW - MIN)); // the cycle ran and published
    const [m] = out.schedule?.fixtures ?? [];
    expect(m?.home.name).toBe('Albania');
    expect(m?.home.flag).toBe('\u{1F1E6}\u{1F1F1}');
  });

  it('a club competition: no flag key at all', async () => {
    seed('uefa.champions', ['MON', 'Monaco'], ['ARS', 'Arsenal']);
    await runRefresh({ source: SOURCE, competition: 'uefa.champions', now: new Date(NOW), jitterMs: 0 });
    const [m] = written('uefa.champions').schedule?.fixtures ?? [];
    expect(m?.home.name).toBe('Monaco');
    expect(m && 'flag' in m.home).toBe(false);
  });
});
